version: '3.8'
services:
  mysql:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    networks:
      - trackkier-network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    networks:
      - trackkier-network
volumes:
  mysql-data:
networks:
  trackkier-network:
