name: Trackkier API CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t usmanashraf033/trackkier-api:latest .

    - name: Push Docker image to Docker Hub
      run: docker push usmanashraf033/trackkier-api:latest

  deploy:
    name: Deploy Docker Image on Self-Hosted Runner
    runs-on: self-hosted

    steps:
      - name: Pull Docker image from Docker Hub
        run: sudo docker pull usmanashraf033/trackkier-api:latest

      - name: Stop Existing Docker Container (if any)
        run: sudo docker stop trackkier-api || true

      - name: Remove Existing Docker Container (if any)
        run: sudo docker rm trackkier-api || true

      - name: Start Docker Container
        run: sudo docker run -d --name trackkier-api -p 80:8080 --env-file ./.env usmanashraf033/trackkier-api:latest

